apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcprocess-deployment
  labels:
    app: orcprocess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orcprocess
  template:
    metadata:
      labels:
        app: orcprocess
    spec:
      serviceAccountName: my-app-sa
      containers:
        - name: orcprocess
          image: orcprocess:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              value:
            - name: AWS_SECRET_ACCESS_KEY
              value:
            - name: AWS_SESSION_TOKEN
              value: SESSION_TOKEN
            - name: BUCKET_NAME
              value: "soat7-fiap-hackaton-2025"
            - name: ELASTICACHE_PASSWORD
              value: "password"
            - name: NAMESPACE
              value: "hackaton-soat7-2025"
            - name: PROCESS_VIDEO
              value: "process-video"
            - name: PROCESS_VIDEO_IMAGE
              value: "process-video:1.0.0"
            - name: REDIS_MID_URL
              value: http://redis-communication-service
            - name: REGION
              value: "us-east-1"
            - name: SHARED_DISK
              value: "/opt/app/shared/"
            - name: UPLOAD_IMAGE
              value: "upload-image"
            - name: UPLOAD_IMAGE_IMAGE
              value: "upload-image:1.0.0"
            - name: UPLOAD_VIDEO
              value: "upload-video"
            - name: UPLOAD_VIDEO_IMAGE
              value: "upload-video:1.0.0"
            - name: MAX_EXECUTION_PER_POD
              value: "2"